name: Hard Test

on:
  workflow_call:
    inputs:
      engine_ref:
        type: string
        description: "Engine branch, tag, or commit"
        required: false
        default: "main"

jobs:
  test-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout testing repo
        uses: actions/checkout@v4
        with:
          path: testing

      - name: Checkout engine repo
        uses: actions/checkout@v4
        with:
          repository: Hynobius-Chess/Hynobius
          ref: ${{ inputs.engine_ref }}
          path: engine

      - name: Configure engine
        shell: pwsh
        run: |
          cmake -S engine -B engine/build -DCMAKE_BUILD_TYPE=Release

      - name: Build engine
        shell: pwsh
        run: |
          cmake --build engine/build --config Release

      - name: Run tests
        shell: pwsh
        run: |
          python tools/test_controler.py \
            --engine Hynobius.exe \
            --tests \
                tests/hard_tests/basic_deflection_200.txt \
                tests/hard_tests/basic_discover_attack_200.txt \
                tests/hard_tests/basic_fork_200.txt \
                tests/hard_tests/basic_hanging_piece_200.txt \
                tests/hard_tests/basic_pin_200.txt \
                tests/hard_tests/basic_skewer_200.txt \
            --pass-rate 90 \