name: Mate Test

on:
  workflow_call:
    inputs:
      engine_ref:
        type: string
        description: "Engine branch, tag, or commit"
        required: false
        default: "main"

jobs:
  test-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout testing repo
        uses: actions/checkout@v4
        with:
          path: testing

      - name: Checkout engine repo
        uses: actions/checkout@v4
        with:
          repository: Hynobius-Chess/Hynobius
          ref: ${{ inputs.engine_ref }}
          path: engine

      - name: Configure engine
        shell: bash
        run: |
          cmake -S engine -B engine/build -DCMAKE_BUILD_TYPE=Release

      - name: Build engine
        shell: bash
        run: |
          cmake --build engine/build --config Release

      - name: Copy engine executable
        shell: bash
        run: |
          mkdir -p testing/bin
          cp engine/build/Hynobius testing/bin/Hynobius
          chmod +x testing/bin/Hynobius

      - name: Run M2
        working-directory: testing
        shell: bash
        run: |
          python tools/test_controler.py \
            --engine bin/Hynobius \
            --tests \
                tests/mate/mate_in_two_1000.txt \
            --pass-rate 100 \

      - name: Run M3
        working-directory: testing
        shell: bash
        run: |
          python tools/test_controler.py \
              --engine bin/Hynobius \
            --tests \
                tests/mate/mate_in_three_1000.txt \
            --pass-rate 100 \

      - name: Run M4
        working-directory: testing
        shell: bash
        run: |
          python tools/test_controler.py \
            --engine bin/Hynobius \
            --tests \
                tests/mate/mate_in_four_200.txt \
            --pass-rate 90 \

      - name: Run M5
        working-directory: testing
        shell: bash
        run: |
          python tools/test_controler.py \
            --engine bin/Hynobius \
            --tests \
                tests/mate/mate_in_five_40.txt \
            --pass-rate 80 \